### ISSUE TITLE
Named exports

### ISSUE THREAD

**Issue by Mister-Hope** [ota-meshi/vuepress-plugin-full-text-search2#24]
Just find this plugin.

We suggest every plugin author to use named exports for better align behavior in both cjs and esm files, you can have a look at what official plugins are doing.

Also we welcome you to add your plugin to https://github.com/vuepress/awesome-vuepress after you add a little more description how to use this plugin and it's options (if it has any).

Also, just a recommandation, you may use name like `vuepress-plugin-full-text-search2` just like our community currectly does.

**Comment by ota-meshi** [comment]
Thank you for letting me know. 

I would like to change it to use named exports 👍 .

> Also we welcome you to add your plugin to https://github.com/vuepress/awesome-vuepress after you add a little more description how to use this plugin and it's options (if it has any).

Currently, I'm not spending a lot of time on this project, so it's difficult to maintain the documentation right now. I think I will make a document after VuePress v2 becomes GA.

> Also, just a recommandation, you may use name like vuepress-plugin-full-text-search2 just like our community currectly does.

I didn't know the naming convention. I named it because I wanted to show that it wasn't a vuepress v1 plugin,

**Comment by Mister-Hope** [comment]
1. Not a full documentation, a little more description on how to use and config it would be nice.

2. In our documentation, we requests all plug-ins beginning with `vuepress-plugin-`

**Comment by ota-meshi** [comment]
> In our documentation, we requests all plug-ins beginning with `vuepress-plugin-`

Yes. I know it :+1:
I mentioned the naming convention as a plugin for VuePress v2 (`vuepress-plugin-xxxxx2`).

**Comment by ota-meshi** [comment]
@Mister-Hope I'm trying to do some work to address this issue, but it looks like VuePress v2's API has changed quite a bit now. I think that plugins have been changed to be used by importing, but is named export still recommended?

**Comment by ota-meshi** [comment]
I think the default export is probably the recommended now.

https://github.com/vuepress/vuepress-next/blob/edbe8a7345aac35ffedcced605baa8827e6ef86d/ecosystem/plugin-back-to-top/src/node/index.ts

**Comment by Mister-Hope** [comment]
Hi there, this is Mr.Hope from VuePress team, I just finished developing `vuepress-plugin-search-pro` at https://vuepress-theme-hope.github.io/v2/search-pro/. This is a plugin having:

1. The plug-in body only loads 3kb code by default, and the search logic is loaded with the index database.

2. The index library uses zlib compression, which can be smaller and loaded asynchronously when the user opens the search page.

3. Support users to create custom index items, such as category, tags, author, writing date, etc.

4. Support historical search record

5. The search results will directly display the matching result type (title, heading, custom index, etc.), and the index content will be accompanied by section heading.

6. Support complete key interaction, and complete A11y support is common soon. We want to ensure all our plug-ins will be friendly to visually impaired.

7. Directly adapt to the default theme, and the theme that supports `@vuepress/plugin-search` will seamlessly support this plug-in.

8. High-speed HMR response, you can update the search index in real time on the development server after it is enabled.

As a author writing similar plugins, we would like you to give some feedbacks to our new plugin, thanks.
