### ISSUE TITLE
How do I change the placeholder "Search"?

### ISSUE THREAD

**Issue by ripperhe** [ota-meshi/vuepress-plugin-full-text-search2#25]
My document is in Chinese and I want the placeholders to appear in Chinese
<img width="237" alt="image" src="https://user-images.githubusercontent.com/13943595/173035642-1abe421e-5a1d-4b48-bdff-bb4c0c159497.png">

**Comment by ota-meshi** [comment]
Currently, it does not support the locale.
It needs to be changed to support the locale. I hope we can provide the same method as "@vuepress/plugin-search".

**Comment by ripperhe** [comment]
Okay, thank you.
