### ISSUE TITLE
【Bug】run localhost success ,but  run on server fail、チェックしていただけないでしょうか☺

### ISSUE THREAD

**Issue by 1211428762** [ota-meshi/vuepress-plugin-full-text-search2#35]
![image](https://user-images.githubusercontent.com/45683072/191249711-ebe29456-7200-4934-a754-30800f0ab950.png)
 env:Windows ,  vite  
    "vuepress": "2.0.0-beta.45",
    "vuepress-plugin-full-text-search2": "^0.4.0",
    
    when I build the project , run on server got errror,   the site other part is ok  ,only the seachbox  render failed.
    I try to change plugin version ,still failed 
    ps: project belong to  company, cant share ,sorry,  
    チェックしていただけないでしょうか

**Comment by ota-meshi** [comment]
If you can't share the repository I can't check.
