### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by qxtang** [ota-meshi/vuepress-plugin-full-text-search2#43]
![image](https://user-images.githubusercontent.com/14085100/201317680-7c1d924c-cb8a-463f-9b50-9fdbe7165ed0.png)
vuepress版本：next
vuepress-plugin-full-text-search2版本：^0.4.0

**Comment by ota-meshi** [comment]
Please provide a repository to reproduce your issue.
