### ISSUE TITLE
BUG: export 'defineClientConfig' (imported as 'defineClientConfig') was not found in

### ISSUE THREAD

**Issue by JenniferHem** [ota-meshi/vuepress-plugin-full-text-search2#67]
When using the plugin I encounter the following error:

ERROR in ./node_modules/vuepress-plugin-full-text-search2/lib/client/clientConfig.js 4:27-45
export 'defineClientConfig' (imported as 'defineClientConfig') was not found in '@vuepress/client' (possible exports: ClientOnly, Content, RouteLink, clientDataSymbol, resolveRoute, resolveRoutePath, resolvers, updateHeadSymbol, useClientData, useLayouts, usePageComponent, usePageData, usePageFrontmatter, usePageHead, usePageLang, usePageLayout, useRedirects, useRoute, useRouteLocale, useRoutePath, useRouter, useRoutes, useSiteData, useSiteLocaleData, useUpdateHead, withBase)
 @ ./docs/.vuepress/.temp/internal/clientConfigs.js 13:0-138 28:2-16
 @ ./node_modules/@vuepress/client/dist/app.js 18:0-56 276:33-46 279:29-50 288:58-71 293:29-42

I would love to keep using the fulltext search. Any ideas how I could prevent the error?

Information: 

node version: v20.11.0
npm version 10.2.4

npm list vue yields:

 @vuepress/bundler-vite@2.0.0-rc.7
│ ├─┬ @vitejs/plugin-vue@5.0.4
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/client@2.0.0-rc.7
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/core@2.0.0-rc.7
│ │ └── vue@3.4.18 deduped
│ ├─┬ vue-router@4.2.5
│ │ └── vue@3.4.18 deduped
│ └─┬ vue@3.4.18
│   └─┬ @vue/server-renderer@3.4.18
│     └── vue@3.4.18 deduped
├─┬ @vuepress/bundler-webpack@2.0.0-rc.7
│ └── vue@3.4.18 deduped
├─┬ vuepress-plugin-full-text-search2@0.4.0
│ └── vue@3.4.18 deduped
├─┬ vuepress-theme-hope@2.0.0-rc.23
│ ├─┬ @vuepress/helper@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-active-header-links@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-back-to-top@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-blog@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-catalog@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-copy-code@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-copyright@2.0.0-rc.13
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-external-link-icon@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-nprogress@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-photo-swipe@2.0.0-rc.13
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-reading-time@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-rtl@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vuepress/plugin-theme-data@2.0.0-rc.12
│ │ └── vue@3.4.18 deduped
│ ├─┬ @vueuse/core@10.7.2
│ │ ├─┬ @vueuse/shared@10.7.2
│ │ │ └─┬ vue-demi@0.14.7
│ │ │   └── vue@3.4.18 deduped
│ │ └─┬ vue-demi@0.14.7
│ │   └── vue@3.4.18 deduped
│ ├── vue@3.4.18 deduped
│ ├─┬ vuepress-plugin-comment2@2.0.0-rc.23
│ │ └── vue@3.4.18 deduped
│ ├─┬ vuepress-plugin-components@2.0.0-rc.23
│ │ └── vue@3.4.18 deduped
│ ├─┬ vuepress-plugin-md-enhance@2.0.0-rc.23
│ │ └── vue@3.4.18 deduped
│ └─┬ vuepress-shared@2.0.0-rc.23
│   └── vue@3.4.18 deduped
└─┬ vuepress@2.0.0-rc.7
  └── vue@3.4.18 deduped

**Comment by smirnoffmv** [comment]
I confirm that the plugin has stopped working

**Comment by JenniferHem** [comment]
Thank you for your confirmation. As the vuepress developers recommend to switch to vitepress we did that a few days ago. So from my side there is no urgency/requirement. But other users might be affected as well.

**Comment by ota-meshi** [comment]
I think it was fixed in #71.
